language: java
deploy:
  provider: releases
  api_key:
    secure: H5mdQNsY/ihYOgY7NF58ahJKjMfl2j7rgtD1HPhk6s3zWrB4TwgRXy3rngSuhn7GfF5LxFe788Vk4WdWcqSrsLpaT1pg0Rabhd0Owdn4ZTbSCuyetphon2/TLCUvwG4VI6z0/NoPytrYO2jyhVeSzIj3pxvZZ8/CzUNjVoqnNOktHyZ8IePSyMj9HjS4Ez8hSM0v4mYkCggneQ5780bCc/F90Gk77xcAdssR+jH8qSUQ0SEZ7KGM3C+v1pMfNUWjZUWUc/ODDpAns4AJiWD3UBC8l5BnBoL6h/rJu06pyqjTPs82MHC3JfEMqq4NmGKf7enbtyqf6Kf69RP6Nc21gF04p/gJcCm3QdwrtuxhWg2VQ0I7k32E6bOWWjaMmqRJcnCo0+ZWOiGag13dStYOII+yHsw0zDbmNFj8MqqLXL52zMrh7kmVGtbVm0bjriDlRrLwI9BuacisMfSDfhhiZIrLjSoRjcEjlczYUbNGA0wwAhlBAK+vus/ppRBqTylIdenxH1iInXeDRDAhtz4PxlN2eJMz0Rd4GUveyd0bQ6ty+SmxDimcgXyta1wRFa7SKp7ZDqMVhuHjG2eMoeZHegOt9HpQlsdu8px+sEaACTn6eL0vD+QWbt4M2Vtp4xLAO964VYT3sZhs2vdl/U63dNZiZa3DW8RlUJFfYWaVm50=
  file_glob: true
  file: build/distributions/JsonToKotlinClass*.zip
  skip_cleanup: true
  on:
    tags: true
    repo: kezhenxu94/JsonToKotlinClass
    all_branches: true